spring:
 jpa:
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
 datasource:
  url: jdbc:postgresql://localhost:5432/testProject
  username: postgres
  password: 4245
